### ISSUE TITLE
Any Plan for Yolov10 TFLite

### ISSUE THREAD

**Issue by quocnhat** [surendramaran/YOLO#1]
Hi, Thank you for your great implementation. 
From the yolov10 report, they are quicker and more accurate than others. Do you think It will be the next popular yolo generation?
Do you have any plan to implement yolov10 tflite for the android devices?
Thanks

**Comment by quocnhat** [comment]
Thanks, looking forward to see it

**Comment by atultiwari** [comment]
hi @surendramaran , any update on this.
you have done an awesome work on yolov8 &v9. I tried to learn myself in the hope that if I can make it work for v10, but I couldnt get it. If you get some time, can you please also make a youtube tutorial on how you are able to figure these out? this would help us a lot.
thank you.

**Comment by surendramaran** [comment]
Yes I am planning to do it as soon as possible, iOS integration is also on
its way. Just time constraints. About YouTube I am not sure but thanks. One
youtuber made a video on this repo so maybe you can watch.

**Comment by atultiwari** [comment]
@surendramaran ,
Thank you for your prompt reply.
i know about some of the youtube videos who originally used your work (both with and without giving proper credits). But they superficially discussed just to change the tflite model and label with our files etc.
what I actually meant was a tutorial for people like me who are interested in techical details on how you analyse the layers of YOLO (e.g. netron like apps) and decide to change the output tensors/array? even a short written description would be helpful if you are not able to make youtube video.
anyways thank you so much for your time and eagerly waiting for the yolov10 version.

**Comment by surendramaran** [comment]
YOLOv10 Android implementation is available now. Thanks.

**Comment by surendramaran** [comment]
@quocnhat I tried YOLOv10 now, and wasn't actually impressed with it, there is always a tradeoff between accuracy and speed. I noticed some accuracy drop in YOLOv10. I think just because it is new it doesn't mean it is better, it still depends on the project that you are doing. If the accuracy is priority you may consider v9 or v8 over v10. My opinion just.

**Comment by quocnhat** [comment]
Thank you for your effort and contribution. 
I just want to compare between ncnn and tflite for my project, and finally ncnn is my choose one.
regards,

**Comment by atultiwari** [comment]
> YOLOv10 Android implementation is available now. Thanks.

Thank you so much
