### ISSUE TITLE
Recommended way of converting Yolov10 to tflite

### ISSUE THREAD

**Issue by atultiwari** [surendramaran/YOLO#4]
Hi,
In the code of Yolov10 you mentioned to upload labels.txt  file if metadata is not attached to the model.

I wanted to know what is the recommended way of converting Yolov10 model to tflite so that metadata is automatically attached with the model.
Thank you.
Atul

**Comment by surendramaran** [comment]
It comes with metadata in all type of export, you should try to run your
model and see if the metadata is available or not.

If the metadata is not available then ultralytics environment will also not
be able to show labels.

So if the metadata is not available then some error happened in exporting.

**Comment by atultiwari** [comment]
Thank you for your reply.
Objects were getting detected from my model, so I asked. it seems in v10 accuracy is dropped compared to v8, as mentioned by one other user too.
Slightly off topic - Since metadata is aleady attached, I wonder, why this coverted tflite is not working with Flutter object detection app example provided by google.
Anyways thank you so much for your support and prompt reply.

**Comment by surendramaran** [comment]
Flutter object detection app take a different model then YOLOv10. If you take model which are trained in TensorFlow https://github.com/tensorflow. then they will work there.

**Comment by atultiwari** [comment]
> Flutter object detection app take a different model then YOLOv10. If you take model which are trained in TensorFlow https://github.com/tensorflow. then they will work there.

ohh
I thought after converting yolov10 model to tflite it should work on flutter object detection app, because my initially assumption was ultimately both are tflite files (one provided by google is tensoflow file exported to tflite and another that I tried was yolov10 exported to tflite).
Thank you so much.

**Comment by LaThanhTrong** [comment]
Can anyone help me how to convert YOLOv10 to tflite as float16?
