### ISSUE TITLE
Should this work in the emulator?

### ISSUE THREAD

**Issue by cjwolff** [surendramaran/YOLO#9]
Hello Surendramaran, 

Thank you for your work on this project.  I am very new to this but I managed to get the program running on an emulator (screenshot attached)

1. I downloaded the YOLOv8l.pt model from ultralytics.
2. I converted to .tflite
3. I opened your project in Android Studio and made sure the path was good.
4. I ran the model.  
5. I see a room but no objects are being detected.  

I'm curious if I missed something.  Should this work in the emulator?

<img width="2070" alt="Screenshot 2024-09-28 at 3 04 55 AM" src="https://github.com/user-attachments/assets/12f0303d-c62b-4f1a-abaa-798f3120d597">

**Comment by cjwolff** [comment]
I had to re-do the model, which took two computers, since tensorflow doesn't work well under Mac M1 silicon.   I managed to get bounding boxes however I don't know about labels yet.  Still working on that part but I appreciate everything you've done.

<img width="459" alt="Screenshot 2024-09-28 at 7 19 12 AM" src="https://github.com/user-attachments/assets/f352aa97-a317-4df7-b721-d8c10b0cd033">

**Comment by surendramaran** [comment]
Yes, the model doesn't have labels I can see, can you share me your tflite
so I can better look?

**Comment by cjwolff** [comment]
Hi Surendaraman,

I was able to fix the problem by including the labels in my script.  Thank you very much for checking in.
